{
  "version": "0.2",
  "phases": {
    "install": {
      "runtime-versions": {
        "nodejs": "12"
      },
    },
    "build": {
      "commands": [
        "cd website",
        "npm install",
        "npm run build"
      ]
    }
  },
  "artifacts": {
    "files": [
      "**/*"
    ],
    "base-directory": "website/public"
  }
}
