baseURL = "http://www.openconstructfoundation.org/"
languageCode = "en-us"
title = "The Open Construct Foundation"
theme = "hugo-tailwind-journal"

[markup.goldmark.renderer]
unsafe= true

[Params]
    tagline = ""


