baseURL = "http://www.openconstructfoundation.org/"
languageCode = "en-us"
title = "The Open Construct Foundation"
theme = "hugo-tailwind-journal"
googleAnalytics = "UA-157500537-1"

[markup.goldmark.renderer]
unsafe= true

[Params]
    tagline = "Making the CDK community better!"
    description = "The Open Construct Foundation aims to create a healthy and productive community around the AWS Cloud Development Kit"


